export const CONFIG_HOST = 'HOST';
export const CONFIG_PORT = 'PORT';

export const CONFIG_DATABASE_TYPE = 'DATABASE_TYPE';
export const CONFIG_DATABASE_HOST = 'DATABASE_HOST';
export const CONFIG_DATABASE_PORT = 'DATABASE_PORT';
export const CONFIG_DATABASE_USERNAME = 'DATABASE_USERNAME';
export const CONFIG_DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const CONFIG_DATABASE_NAME = 'DATABASE_NAME';
export const CONFIG_DATABASE_PATH = 'DATABASE_PATH';
export const CONFIG_DATABASE_LOGGING_ENABLED = 'DATABASE_LOGGING_ENABLED';
export const CONFIG_DATABASE_SYNCHRONIZE = 'DATABASE_SYNCHRONIZE';

export const CONFIG_ENVIRONMENT = 'ENVIRONMENT';
